import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import DocItem from '@theme/DocItem';

function auto(dirName: string): SidebarItemAutogenerated {
  return { type: 'autogenerated', dirName: dirName }
};

const offsetBars: SidebarsConfig = {
  initBar: [auto('offset')],
}

const contribBars: SidebarsConfig = {
  initBar: [auto('contrib')],
}

const sidebars: SidebarsConfig = {
  homebar: [{
    type: "doc",
    id: "index"
  }],
  ...offsetBars,
  ...contribBars,
}

export default sidebars
