import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import DocItem from '@theme/DocItem';

function auto(dirName: string): SidebarItemAutogenerated {
  return { type: 'autogenerated', dirName: dirName }
};

const offsetBars: SidebarsConfig = {
  mainBar: [auto('offset/main')],
  playerBar: [auto('offset/player')],
  cunitBar: [auto('offset/cunit')],
  orderBar: [auto('offset/order')],
  imageBar: [auto('offset/image')],
  unitBar: [auto('offset/unit')],
  etcBar: [auto('offset/etc')],
}

const contribBars: SidebarsConfig = {
  initBar: [auto('contrib')],
}

const sidebars: SidebarsConfig = {
  homebar: [{
    type: "doc",
    id: "index"
  }],
  ...offsetBars,
  ...contribBars,
}

export default sidebars
