import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

function auto(dirName: string): SidebarItemAutogenerated {
  return { type: 'autogenerated', dirName: dirName }
};

const offsetBars:SidebarsConfig = {
  initBar: [auto('offset')],
}

const sidebars:SidebarsConfig = {
  ...offsetBars
}

export default sidebars
